### ISSUE TITLE
Allow creation of catalog or profile from XLS

### ISSUE THREAD

**Issue by deenine** [oscal-compass/compliance-trestle#1020]
## Issue description / feature objectives

This feature would allow bootstrapping of trestle environment where a oscal json catalog does not exist, or incorporating an existing compliance program's profile into a trestle environment. 

This could be implemented by passing in a CSV of the catalog/profile and a yaml file that maps columns to oscal fields, for example:
- id: 0
- sort-id: 1
- control group*: 2
- title: 3

This would simple to implement, but would become more complicated when attempting to parse lists of parameters or control parts. Maybe MVP looks like the above?

*aka 'control family', e.g. 'Access Control', 'Incident Response'

**Comment by vikas-agarwal76** [comment]
similar to #950
