### ISSUE TITLE
OCP4 Demo for Kubecon

### ISSUE THREAD

**Issue by vikas-agarwal76** [oscal-compass/compliance-trestle#1177]
## Issue description / feature objectives
Need to create a demo for showing agile authoring of OCP4 catalogs, profiles, CD, and SSP

## Completion Criteria
Create following repos in compliance-trestle-testing with "Public" visibility.
- ocp4-catalogs
- ocp4-profiles
- ocp4-cd
- ocp4-ssp

Inititalize trestle in each repo, copy the directory structure from test-profile and the related automation (with main, dev branch, automation, release, etc.).

1. Setup of ocp4-catalogs repo
Use the instructions in https://ibm.github.io/compliance-trestle/tutorials/task.ocp4-cis-profile-to-oscal-catalog/transformation/  to setup conversion from text file to OSCAL catalog JSON.
Rest of the automation from OSCAL to Markdown and back, semantic versioning, approval, etc. should be similar to that in test-profiles repo.  
Add Anca to the list of approvers in CODEOWNERS file.
Setup push to profile repo in case of updates to the catalog.

Detailed setup for other repos will be added later.

**Comment by vikas-agarwal76** [comment]
### Setup of ocp4-profiles repo
The initial profile will be in OSCAL json. There will be no script to convert any xslx/text files to OSCAL json. The initial profile is - 
[roks-ocp4-tailored.json.txt](https://github.com/IBM/compliance-trestle/files/9575766/roks-ocp4-tailored.json.txt)

profile name should be "roks-ocp4-tailored".
Rest of the automation from OSCAL to Markdown and back, semantic versioning, approval, etc. should be similar to that in test-profiles repo.
Add Anca to the list of approvers in CODEOWNERS file.

**Comment by vikas-agarwal76** [comment]
### Setup of ocp4-cd repo
The initial CD will be in CSV format. Use CSV to OSCAL CD task (from Lou) to convert CSV to OSCAL json. The sample CD csv fie is -
[ocp4-cd.csv](https://github.com/IBM/compliance-trestle/files/9598130/ocp4-cd.csv)

CD name should be "ocp4-cis-node".
Rest of the automation from OSCAL to Markdown and back, semantic versioning, approval, etc. should be similar to that in test-profiles repo.
Add Anca to the list of approvers in CODEOWNERS file.

**Comment by enikonovad** [comment]
@vikas-agarwal76 I was not able to find task to convert csv to OSCAL. Currently, we have [xlsx to OSCAL task](https://ibm.github.io/compliance-trestle/cli/#trestle-task-xlsx-to-oscal-cd) and [CIS profile to OSCAL](https://ibm.github.io/compliance-trestle/tutorials/task.ocp4-cis-profile-to-oscal-cd/transformation/)

Did you mean xlsx to OSCAL conversion or is there a new script somewhere?

**Comment by vikas-agarwal76** [comment]
@enikonovad 
### Setup of ocp4-ssp repo
copy the content from ocp4-cd repo and create folders for ssp. SSP name should ocp4-ssp.

Disable the automation currently (travis.yaml file). Will manually create an SSP for demo purposes as SSP commands need to be updated to use component defs.

setup SSP update.sh in cp4-cd repo to push the contents here in case of CD updates.

**Comment by degenaro** [comment]
See initialized:
https://github.com/ComplianceAsCode/kube-oscal-cd
https://github.com/ComplianceAsCode/kube-oscal-catalog

Set not initialized:
https://github.com/ComplianceAsCode/kube-oscal-ssp
https://github.com/ComplianceAsCode/kube-oscal-profile
