### ISSUE TITLE
Update to flake8 6.x.x

### ISSUE THREAD

**Issue by enikonovad** [oscal-compass/compliance-trestle#1258]
## Issue description / feature objectives
Recently flake8 released a version 6.0.0 which seemed to drop the support of Python 3.7. The change broke flake8-broken-line plugin. As a result `pre-commit autoupdate` has been temporary disabled.

This issue is to track the changes to the flake8-broken-line and other plugins as they move to flake8 6.0.0+. Once the move have been completed `pre-commit autoupdate` should be enabled.

## Caveats / Assumptions
Blocker to track: https://github.com/wemake-services/flake8-broken-line/issues/281

## Completion Criteria
Revert changes to `makefile` and enable `pre-commit-update` when either `code-format`, `code-lint` or `mdformat` is ran.

**Comment by degenaro** [comment]
in setup.cfg flake8 specification has no version restrictions, so the current is being used. In my python venv for the trestle develop branch using `make develop`:
```
flake8 --version
7.0.0 (mccabe: 0.7.0, pep8-naming: 0.13.3, pycodestyle: 2.11.1, pyflakes: 3.2.0) CPython 3.10.12 on Linux
```
