### ISSUE TITLE
Drop support for python 3.7, 8 and add 3.10 - so support is only for 3.9 and 3.10

### ISSUE THREAD

**Issue by fsuits** [oscal-compass/compliance-trestle#1314]
## Issue description / feature objectives
The downloads from PyPI as shown by https://pypistats.org/packages/compliance-trestle show very few downloads for python 3.7 or 3.8
3.9 and 3.10 are popular now, so it seems now is a good time to switch

This would unblock #1258

**Comment by degenaro** [comment]
Fixed #1533
