### ISSUE TITLE
Extend mixed template document processing 

### ISSUE THREAD

**Issue by jayhawk87** [oscal-compass/compliance-trestle#1424]
## Issue description / feature objectives

Today, when processing a folder with mixed template, only a single document whose name matches the template name is supported. Additional files of the template type are ignored.

As a document maintainer, it would be nice if trestle would check all files instances of each template type located in a single document folder. 

Example:

```
root folder
     |
     + --- file1.md identified as coming from template `a`
     |
     + --- file2.md identified as coming from template `b`
     |
     + --- file3.md identified as coming from template `b`
     |
     ...
```

## Completion Criteria

As a document maintainer, I should be able to create different documents coming from different templates in the same directory as well as using same template for different documents with not different names

**Comment by AleJo2995** [comment]
@jayhawk87 we need some clarification here. First, let's put some context.

Right now, trestle is performing validation on `trestle author folders validate` based on name, as you might already now, so just for recap, for example: if we have `template_a`, `template_b`, created files would need to be named `template_a`, `template_b` as well so the validation can be performed. Besides that all templates would need to be present and no other files will be validated.

Now, We´ve had some discussion around between @vikas-agarwal76 , @mrgadgil  and I and we could just go with validating documents in this way: `whateverfilename_template_a`, `whateverfilename_template_b` , `whateverfilename2_template_a`. So in this way we can have more than 1 instance of files coming from the same template, but **still** having at least 1 instance of each template defined initially.

Will this work for matching the use case you need? 

Other than that, we could be performing a validation against header value `type` in the template but that will take more changes and will require a change in `trestle author docs validate `command to keep consistency between the 2 commands
