### ISSUE TITLE
Write documentation on Trestle Plan, Action and Element

### ISSUE THREAD

**Issue by leninmehedy** [oscal-compass/compliance-trestle#145]
We need to document the concept, architecture of Trestle Plan and Action. The documentation should also include guide and example on creating a Trestle Plan. The document should reside in the `/docs` folder for now.

**Comment by butler54** [comment]
This should all be done in docstrings in the classes and referred to in the markdown documentations.

**Comment by vikas-agarwal76** [comment]
Enhance the documentation in actual commands.
