### ISSUE TITLE
task csv-to-oscal-cd should support column $Component_Purpose

### ISSUE THREAD

**Issue by degenaro** [oscal-compass/compliance-trestle#1460]
## Issue description / feature objectives

If optional column $Component_Purpose is specified in csv it should map to the `purpose` field of OSCAL Component Definition.

## Caveats / Assumptions

N/A

## Completion Criteria

Code to support and corresponding tests delivered.

**Comment by jpower432** [comment]
Closed due to inactivity. This can be reopened if there is a need.
