### ISSUE TITLE
Trestle Roadmap

### ISSUE THREAD

**Issue by vikas-agarwal76** [oscal-compass/compliance-trestle#1480]
Here is the roadmap for trestle for next few months. This list will be kept updated.

- Update trestle to latest OSCAL version v1.1.1
  - New feature requests have been frozen and a new release will be made with additional features in develop.
  - Any bug fixes to current version will continue
  - Current version will be supported for at least 90 days after release of new trestle version with latest OSCAL 
- OSCAL support for CRM in Component Definition
  - CRM would be added to future release of OSCAL
  - Trestle will add support once it is released
- OSCAL support for Mapping model
  - Working with NIST for mapping model support in OSCAL
  - Trestle will add mapping model functionality once it is released
- POAM authoring
  - High level POAM authoring design for FedRAMP is ready
  - Trestle will add support based on prioritization of this requirement after move to OSCAL v1.1.1

**Comment by jpower432** [comment]
@vikas-agarwal76 We discussed in the last issue review that this issue may need to be represented a different way. Could this be decomposed into Epics and represented in a GitHub project or maybe through a ROADMAP.md file in the repo? Perhaps we could discuss a standardized method for organization.
