### ISSUE TITLE
We've moved

### ISSUE THREAD

**Issue by degenaro** [oscal-compass/compliance-trestle#1482]
## Describe the bug

Location of `compliance-trestle` has been moved to `github.com/oscal-compass`. Corresponding changes to webpages are needed.

## To be done: high priority

1. Fix mkdocs.yml in 2 places
2. Add banner to README with construction icon calling attention to new location, since old location will eventually be unsupported
3. Identify any other links that are broken and fix

## Expected behavior

All links should work and users should plainly see that the `compliance-trestle` location has moved.

## Screenshots / Logs.

N/A

## Environment

N/A

**Comment by mrgadgil** [comment]
@degenaro Can we close this issue?

**Comment by degenaro** [comment]
Yes, as far as I'm concerned. Please do so or let me know if I should...

Lou.

**Comment by mrgadgil** [comment]
@deenine Hello The site is working as design. compliance trestle publishes to github pages at the url https://oscal-compass.github.io/compliance-trestle/

Individual repositories in the the github organization will publish to https://oscal-compass.github.io/<repository>/

**Comment by deenine** [comment]
Maybe its worth adding a top level page at https://oscal-compass.github.io that describes the overall oscal-compass project and points at the various sub repos, rather than having it 404?

**Comment by mrgadgil** [comment]
@deenine Thank you for the suggestion. I have created an issue for the fix: https://github.com/oscal-compass/compliance-trestle/issues/1497

**Comment by mrgadgil** [comment]
I will close this issue as the move is completed.
