### ISSUE TITLE
Review trestle website links and make sure all are operational

### ISSUE THREAD

**Issue by degenaro** [oscal-compass/compliance-trestle#1484]
## Describe the bug

Some links may links to other sites, e.g. NIST OSCAL, may not be working, e.g. due to relocation. 

## To Reproduce

Check external links. If all are working, then there is nothing to do. Otherwise, fix or remove broken links.

## Expected behavior

All links should work.

## Screenshots / Logs.

N/A

## Environment

N/A

**Comment by AleJo2995** [comment]
Can we move this one to the next milestone? Doesn´t seem a high priority to me at the moment

**Comment by jpower432** [comment]
Closing this issue in favor of an automated approach to verification.
