### ISSUE TITLE
Support for OSCAL version 1.1.1?

### ISSUE THREAD

**Issue by deenine** [oscal-compass/compliance-trestle#1494]
## Issue description / feature objectives

The current version of OSCAL json from https://github.com/usnistgov/oscal-content/tree/main/nist.gov/SP800-53/rev5/json is 1.1.1:

`"metadata": {
      "title": "NIST Special Publication 800-53 Revision 5.1.1 HIGH IMPACT BASELINE",
      "last-modified": "2023-12-15T20:25:00.649143Z",
      "version": "5.1.1+u2",
      "oscal-version": "1.1.1",`

However, when attempting to use with trestle, it errors with:

`OSCAL version: 1.1.1 is not supported, use 1.0.4 instead. (type=value_error)`

Is there a plan to support OSCAL 1.1.1?

**Comment by deenine** [comment]
Thanks @AleJo2995 I missed the roadmap issue. Maybe add a link to it from the readme? 

I'll try and get along to a community call to say hello.

**Comment by JoseGHdz** [comment]
> Hi @deenine . You're completely right, with the current code base OSCAL v.1.1.1 is not supported, instead v1.0.4 is the only one supported.
> 
> Currently as you can see in issue #1480, that's the actual work mapped for starting to work on next weeks. So keep up to date in here for new announcements.
> 
> Also, I'd really like to invite you our community calls happening on Tuesdays every 2 weeks where we make announcements and give details on our current development status. You can find more information about it [here](https://github.com/oscal-compass/compliance-trestle?tab=readme-ov-file#community-call)
> 
> Thanks

Hello, I just ran into this issue with the SSP I created. Do you know if there have been any updates to transition from 1.0.4 to 1.1.1?

**Comment by degenaro** [comment]
The trestle develop branch supports the latest OSCAL (1.1.2). You can try
that until the next release of trestle.
