### ISSUE TITLE
Internal failure when using ssp-assemble with the FedRAMP Rev 5 High profile

### ISSUE THREAD

**Issue by jpower432** [oscal-compass/compliance-trestle#1502]
## Describe the bug

Using `ssp-assemble` with the FedRAMP Rev5 High [profile](https://github.com/GSA/fedramp-automation/blob/5f44c1b09af13d203f008be6bd33603ad7cb0202/dist/content/rev5/baselines/json/FedRAMP_rev5_HIGH-baseline_profile.json) (OSCAL 1.0.4) version results in an internal error.

## To Reproduce

For the reproduction steps, I am using the `compliance-trestle-ssp-demo` [repo](https://github.com/IBM/compliance-trestle-ssp-demo).

1. Import the profile and NIST catalog (OSCAL 1.0.4) into your trestle workspace
```bash
trestle import -f "https://raw.githubusercontent.com/usnistgov/oscal-content/690f517daaf3a6cbb4056d3cde6eae2756765620/nist.gov/SP800-53/rev5/json/NIST_SP-800-53_rev5_catalog.json" -o nist_800_53

trestle import -f "https://raw.githubusercontent.com/GSA/fedramp-automation/5f44c1b09af13d203f008be6bd33603ad7cb0202/dist/content/rev5/baselines/json/FedRAMP_rev5_HIGH-baseline_profile.json" -o fedramp_rev5_high

trestle href --name "fedramp_rev5_high" -hr "trestle://catalogs/nist_800_53/catalog.json"
```
3. Generate the SSP markdown
```bash
trestle author ssp-generate -cd ACME_comp_def --profile fedramp_rev5_high --output md_ACME_platform_ssp -y assets/extra-ssp-metadata.yml
```
4. Run `ssp-assemble`
`trestle author ssp-assemble -m md_ACME_platform_ssp -cd ACME_comp_def -o ACME_SSP`
6. Observe the error
`trestle.core.commands.author.ssp:94 ERROR: Error while assembling SSP: Internal error seeking by_comp for component de43e95b-630d-4931-ae10-1b7fd4317446 and statement ac-2.3_fr`

## Expected behavior

Successful SSP assembly

## Environment

- OS: \[e.g. iOS\] Fedora 36
- Python version: Python 3.10.11
- Installed packages: Trestle version v2.5.0 based on OSCAL version 1.0.4

**Comment by degenaro** [comment]
I get the same error. 
1. I installed the current develop branch of trestle in a venv and activated
2. I fetched the demo repo
3. I had to remove `compliance-trestle-ssp-demo/catalogs/NIST_800-53_r4/catalog.json` because import complained `already exists`.
4. ssp-generate resulted in a plethora of `has no values and was referenced by prose` warnings.
5. ssp-assemble resulted in a few `not in profile` warnings followed by the failure.

**Comment by jpower432** [comment]
Adding more information I have found about the issue here:

- The control part ending in `_fr` added by the FedRAMP profile does not have a label property
- It is added to the `part_id_map_by_label` with an empty key value [here](https://github.com/oscal-compass/compliance-trestle/blob/218ffe47a879e8bbca115bd956cfc9e99bbc5751/trestle/core/commands/author/ssp.py#L554).
- The `comp_info_dict` is being created with an empty label intentionally [here](https://github.com/oscal-compass/compliance-trestle/blob/218ffe47a879e8bbca115bd956cfc9e99bbc5751/trestle/core/control_reader.py#L239) to denote a top-level response.
- The empty label matches with the `_fr` control part [here](https://github.com/oscal-compass/compliance-trestle/blob/218ffe47a879e8bbca115bd956cfc9e99bbc5751/trestle/core/catalog/catalog_reader.py#L262) because both keys are empty strings.
