### ISSUE TITLE
Docs (and/or GitHub): https://github.com/IBM/compliance-trestle-demos has not been moved to new org

### ISSUE THREAD

**Issue by asaba-hashi** [oscal-compass/compliance-trestle#1506]
## Describe the bug

The links to the demos on https://oscal-compass.github.io/compliance-trestle/demonstrations-content/ have been updated to point to the new org at "https://github.com/oscal-compass/compliance-trestle-demos/tree/develop/trestle_flask_api", for example, but that repository has not been moved.

## To Reproduce

N/A

## Expected behavior

The link 

## Screenshots / Logs.

N/A

## Environment

N/A

**Comment by degenaro** [comment]
It looks to me like [https://github.com/IBM/compliance-trestle-demos](https://github.com/IBM/compliance-trestle-demos) has been moved to [https://github.com/oscal-compass/compliance-trestle-demos](https://github.com/oscal-compass/compliance-trestle-demos). Am I wrong?

**Comment by degenaro** [comment]
![Screenshot from 2024-05-06 13-31-54](https://github.com/oscal-compass/compliance-trestle/assets/520029/7f25fbf5-675f-4c56-ad0b-49f212b0a2e0)

**Comment by asaba-hashi** [comment]
Yes, thanks for following up, it hadn't been moved when when I opened this issue 3 months ago.
