### ISSUE TITLE
Update all github actions pipelines to latest versions and introduce dependabot

### ISSUE THREAD

**Issue by butler54** [oscal-compass/compliance-trestle#1541]
## Issue description / feature objectives

Github actions has been iterating rapidly. CICD tools are high risk from a security perspective. Move to the latest versions of all actions steps if possible and introduce dependabot to ensure versions are updated.

Historically dependabot provided minimal value as it did not index setup.cfg files. This appears to be closed.

## Caveats / Assumptions

No breaking changes have been introduced that have adverse affects outside of the github actions pipelines themselves (e.g. on the managed code)>

**Comment by jpower432** [comment]
@AleJo2995 Is this issue should I can assist with? Looking to document this as part of https://github.com/oscal-compass/community/issues/4.

**Comment by AleJo2995** [comment]
@jpower432 I think so, it would be helpful some assistance from you if you already have an idea in mind. I haven't started with this one yet, I was focusing on the other ones. Thanks
