### ISSUE TITLE
Add RISK support in to component definition spread sheet (csv) support 

### ISSUE THREAD

**Issue by degenaro** [oscal-compass/compliance-trestle#1544]
## Issue description / feature objectives

Add the following optional columns as expected but optional to the csv-to-oscal-cd task:

- $Original_Risk_Rating
    - Provide the Original Risk Rating from the scanner
- $Adjusted_Risk_Rating
    - Provide the Adjusted Risk Rating as approved by the CIO
- $Risk_Adjustment
    - Whether there was a Risk Adjustment

These values, if specified, are to be added to the resulting OSCAL component definition as Properties.

## Caveats / Assumptions

Provide sample/test/tutorial csv's with these additional fields/descriptions.

## Completion Criteria

Test cases for code coverage added.

**Comment by Ma1h01** [comment]
Do risk-related columns need special handling? For example, they are ignored or required for validation component type?

**Comment by degenaro** [comment]
For validation, ignored. Otherwise, handling is the same for other optional
columns that become OSCAL properties.
