### ISSUE TITLE
Support multiple version of trestle docs using `mike` or similar on mkdocs website.

### ISSUE THREAD

**Issue by butler54** [oscal-compass/compliance-trestle#1547]
## Issue description / feature objectives
As trestle grows in complexity it's likely that multiple versions of the documentation is required, as the trestle website also supports API docs. [`mike`](https://pypi.org/project/mike/0.3.4/) allows multiple versions to be displayed correctly with a drop down.

## Caveats / Assumptions
- mike is used
- Versioning (until stability) is based off of every unique sem-ver release
- no branch based builds.
## Completion Criteria

- Trestle documentation website correctly releases along with a version published to pypi.
- Default version correctly points to latest

**Comment by AleJo2995** [comment]
I´m re-assigning this to me instead, but I don´t see it happening for next milestone as this doesn´t seem to be a high priority item for now

**Comment by butler54** [comment]
Hey @AleJo2995  if you haven't done much I can take this on.

**Comment by butler54** [comment]
Got a question on this with respect to the structure, in particular 'default's for versions. 

In scope: 
- each release has a version of the documentation
- The default view is the latest *released* code
- Develop branch is also included as 'Develop' but it is *not* default. This release will get automatically updated each branch
Out of scope:
- Branch / PR based builds of the website.
