### ISSUE TITLE
Update release pipeline to use the latest versions of python-semantic-release

### ISSUE THREAD

**Issue by butler54** [oscal-compass/compliance-trestle#1548]
## Issue description / feature objectives
https://python-semantic-release.readthedocs.io/en/latest/ behaviour has changed significantly. Update workflows such that given update will upload github releases and pypi releases.

This is required to move to pydantic 2.0 e.g. in PR #1533

## Caveats / Assumptions
- will need to be end to end tested with a fork into a 'test' pypi repo
- 

## Completion Criteria
- Demonstrated in isolation in a test repo
- One successful release completed.

**Comment by jpower432** [comment]
Closed by #1564
