### ISSUE TITLE
Point to nist-source directly instead of using schema in `release-schemas` directory

### ISSUE THREAD

**Issue by AleJo2995** [oscal-compass/compliance-trestle#1549]
## Describe the bug

Investigate if possible to point at using the schema directly coming from nist-source instead of using a downloaded json schema. Probably not going to be able to do it as the schema organization and generation has changed, but still worth the try.

## To Reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

## Environment

- OS: \[e.g. iOS\]
- Python version:
- Installed packages:

**Comment by butler54** [comment]
Updated title to reflect current issues in develop.

**Comment by butler54** [comment]
Had a quick look at this and it's a little different to I thought.

*TL;DR;* Move to downloading OSCAL artifacts via github releases. This will necessitate some changes in the build pipeline but it should be a relatively small activity.

It also should have the advantage of loosening the coupling to the upstream NIST projects which will make it easier for people in airgapped environments.
