### ISSUE TITLE
Check if python semantic release publish has support for removing/reverting tags/releases if not successful

### ISSUE THREAD

**Issue by AleJo2995** [oscal-compass/compliance-trestle#1571]
## Describe the bug

Quite recently, we have experimented a few issues related to the release process. While attempting to do a deployment, we had a problem while publishing the project to PyPi. According to the error, the email used to be published (vikas´s) needed to be verified from his account to publish the package. Once the email was verified, we re-tried the deploy again but it was not possible due to the tag for the current version already existed because it was created before the package tried to be published to PyPi.

## To Reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

## Expected behavior

Ideally if the process fails after all, it should be handling the things created in a way that can be revertible or not affect the re run of the process.

## Screenshots / Logs.

Verify email error:

![image](https://github.com/oscal-compass/compliance-trestle/assets/8278478/a3723c68-6f5e-4ed4-a378-8a9fe4f07a47)

Release tag already exists error:

![image](https://github.com/oscal-compass/compliance-trestle/assets/8278478/8bc7671d-2883-420b-90df-e363e7a0553d)

## Environment

- OS: \[e.g. iOS\]
- Python version:
- Installed packages:

**Comment by butler54** [comment]
So this should be possible by decoupling the stages in the actions pipelines.

It's something I can look into.
