### ISSUE TITLE
Trestle author -tv flag doesn't enforce the version format (e.g. 0.0.1) correctly

### ISSUE THREAD

**Issue by Ma1h01** [oscal-compass/compliance-trestle#1586]
## Describe the bug
Invalid version formats (e.g. 1a2b3) are not captured when using the `trestle author header -tv` command. This behavior is due to the . character is not escaped properly in `is_valid_version()` under `template_versioning.py`.

A fix might look like this:
<img width="406" alt="image" src="https://github.com/oscal-compass/compliance-trestle/assets/78010183/685f98cf-8a83-4f0f-8b41-8e2c60ba622e">

## To Reproduce

` trestle author headers setup -tn my_task -tv 1a2b3`

## Expected behavior

The program should throw an error, and the task folder should not be created.

## Screenshots / Logs.
After executing the above command:
<img width="303" alt="image" src="https://github.com/oscal-compass/compliance-trestle/assets/78010183/07754145-6e73-4b0b-bb38-05576d01d559">

## Environment

- OS: \[e.g. iOS\]
- Python version:
- Installed packages:

**Comment by AleJo2995** [comment]
@Ma1h01 you're right, this is a bug, I have confirmed, go ahead and work on it.

Could you please also take a look at this Sonar lint code suggestion and see if it makes any sense? It seems to be a readability and ease of use suggestion. Reference here https://www.quora.com/Is-there-any-difference-between-the-regular-expressions-0-9-and-d

I happen to have sonnar-lint extension installed on Code which is highlighting already that suggestion.

![image](https://github.com/oscal-compass/compliance-trestle/assets/8278478/4f0a400f-7663-4e42-8a12-4c52532d7e0b)


 Thanks 👍

**Comment by Ma1h01** [comment]
@AleJo2995 
Both character classes specify digits from 0-9. However, `\d` also allows digits from different language systems (e.g. Arabic) whereas `[0-9]` only allows Latin digits.
I'd suggest we stick with `[0-9]` as Latin digits are more universal.
