### ISSUE TITLE
trestle author ssp-generate does not seem to do the correct thing with `aggregates` parameters

### ISSUE THREAD

**Issue by rahearn** [oscal-compass/compliance-trestle#1596]
## Describe the bug

For `aggregates` parameters (such as `si-7_prm_1` from https://raw.githubusercontent.com/usnistgov/oscal-content/main/nist.gov/SP800-53/rev5/json/NIST_SP-800-53_rev5_catalog.json) ssp-generate is showing a warning about `the parameter has no values and was referenced by prose` and the markdown ends up with the `label` field inserted, rather than the values aggregated from `si-07_odp.01`, `si-07_odp.02`, and `si-07_odp.03`.

## To Reproduce

1. Import the following profile: [profile.json](https://github.com/user-attachments/files/15960680/profile.json)
1. Run `trestle author ssp-generate -p imported-profile -o markdown`
1. Note the warnings about values
1. Open the `markdown/si-7.md` file
1. See that the content from the various parameters are set in the assessment objective section, but not in the control statement

## Expected behavior

I'd expect there to be no warning about missing values, since the individual aggregated parameters are present, and the control statement output to reference the set parameters instead of the generic catalog label.

## Environment

- OS: macOS / Docker 
- Python version: python-3.11.9-slim docker image
- Installed packages: trestle 3.2.0

**Comment by AleJo2995** [comment]
Hi @rahearn . Just wanted to reach out and let you know that I will be looking at this issue and give feedback about it soon. Thanks for reaching out and will contact again soon.

**Comment by AleJo2995** [comment]
@rahearn the PR has been linked to the issue, if you want to take a look at it. Thanks
