### ISSUE TITLE
Make sure compliance-trestle demos are running correctly - Creating a CIS controls catalog from an excel spreadsheet.

### ISSUE THREAD

**Issue by AleJo2995** [oscal-compass/compliance-trestle#1601]
## Describe the bug

Compliance trestle demos [repo](https://github.com/oscal-compass/compliance-trestle-demos) is outdated and needs refreshment and review. 

It is needed to go through the [Creating a CIS controls catalog from an excel spreadsheet](https://github.com/oscal-compass/compliance-trestle-demos?tab=readme-ov-file#creating-a-cis-controls-catalog-from-an-excel-spreadsheet) review it runs correctly as the documentation specifies concretely for this one.

Compliance-trestle version used for the generation of the demos is too outdated now vs the current one, so as part of the revision, it should be ideal to run the demo with the latest version and see if anything has changed or needs refreshment.

If there is anything needed to be done there by the demo, please submit a PR against the repo to be reviewed and tracked. 

## To Reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

## Environment

- OS: \[e.g. iOS\]
- Python version:
- Installed packages:

**Comment by Ma1h01** [comment]
This demo uses an obsolete method, and REAMD needs to be reworked. I've made a pull request for them.

**Comment by AleJo2995** [comment]
Closing as to passing to compliance-trestle demos repo
