### ISSUE TITLE
Make sure compliance-trestle demos are running correctly - Task Examples

### ISSUE THREAD

**Issue by AleJo2995** [oscal-compass/compliance-trestle#1604]
## Describe the bug

Compliance trestle demos [repo](https://github.com/oscal-compass/compliance-trestle-demos) is outdated and needs refreshment and review. 

It is needed to go through the [Task Examples](https://github.com/oscal-compass/compliance-trestle-demos?tab=readme-ov-file#task-examples) review it runs correctly as the documentation specifies concretely for this one.

Compliance-trestle version used for the generation of the demos is too outdated now vs the current one, so as part of the revision, it should be ideal to run the demo with the latest version and see if anything has changed or needs refreshment.

If there is anything needed to be done there by the demo, please submit a PR against the repo to be reviewed and tracked. 

## To Reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

## Environment

- OS: \[e.g. iOS\]
- Python version:
- Installed packages:

**Comment by Ma1h01** [comment]
Two task demos work fine with the current version of the trestle. Updates are not needed.

**Comment by AleJo2995** [comment]
Thanks @Ma1h01 . Closing it
