### ISSUE TITLE
Make sure compliance-trestle demos are running correctly - Trestle as Foundation Examples

### ISSUE THREAD

**Issue by AleJo2995** [oscal-compass/compliance-trestle#1605]
## Describe the bug

Compliance trestle demos [repo](https://github.com/oscal-compass/compliance-trestle-demos) is outdated and needs refreshment and review. 

It is needed to go through the [Trestle as Foundation Examples](https://github.com/oscal-compass/compliance-trestle-demos?tab=readme-ov-file#trestle-as-foundation-examples) review it runs correctly as the documentation specifies concretely for this one.

Compliance-trestle version used for the generation of the demos is too outdated now vs the current one, so as part of the revision, it should be ideal to run the demo with the latest version and see if anything has changed or needs refreshment.

If there is anything needed to be done there by the demo, please submit a PR against the repo to be reviewed and tracked. 

## To Reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

## Environment

- OS: \[e.g. iOS\]
- Python version:
- Installed packages:

**Comment by Ma1h01** [comment]
After following the demo, I found three issues that prevented the demo from being executed successfully.
1. 
<img width="748" alt="image" src="https://github.com/oscal-compass/compliance-trestle/assets/78010183/aacf9895-5d66-48be-92d2-819b8e0309d9">
The demo runs with the trestle version `1.1.0`. This resulted in an import issue as the old version imports the `ModelField` from `pydantic.fields`, which is not supported in the currently used pedantic version. Simply changing the version of the installed trestle can resolve the issue.

2. `ControlSelection` and `ReviewedControls` are moved to the `trestle.oscal.common` module but imported from the old module `trestle.oscal.assessment_results`  in  `k8s-to-oscal.py`. Updating the import statement can resolve the issue.

3. Two sample YAML files don't have the `labels` fields, which results in `KeyError` expectation, and a `None` value is passed to an object monitored by pydantic; thus, fails the entire execution.

**Comment by AleJo2995** [comment]
Thanks @Ma1h01 . Moving this issue to [compliance-trestle-demos](https://github.com/oscal-compass/compliance-trestle-demos). Closing.
