### ISSUE TITLE
Update authors information in project metadata to reflect CNCF community

### ISSUE THREAD

**Issue by butler54** [oscal-compass/compliance-trestle#1721]
## Describe the bug

Current authors information in PYPI states IBM is the author and lists @vikas-agarwal76's email

## To Reproduce

Visit here: https://pypi.org/project/compliance-trestle/
 

## Expected behavior

- This should be the oscal-compass developers / community
- Perhaps a google group email?

## Screenshots / Logs.

NA

## Environment

ALL

**Comment by jpower432** [comment]
@butler54 After some discussion in this issue review, we propose that the name and email be `OSCAL Compass` and the oversight committee mailing list respectively. What do you think?
