### ISSUE TITLE
Perf: Fix redundency in `trestle add` command

### ISSUE THREAD

**Issue by aNebula** [oscal-compass/compliance-trestle#209]
## Issue description / feature objectives
To allow chained add of multiple elements to a element path, currently, `AddCmd.add()` computes the new parent element by applying the addition of child element. This is to prepare the parent element for the `UpdateAction` to add the next element in chain. This is a redundency, as  this update of parent element outside of action plan is same as the `UpdateAction`.
## Completion Criteria
This could potentially be solved by adding a new action called `AddAction`, which, returns the updated parent element to the next addition in the chain.

**Comment by butler54** [comment]
Can you review this? I think that we may have solved it?

**Comment by butler54** [comment]
TBD whether this needs to be fixed or not.

**Comment by jpower432** [comment]
@butler54 We are reviewing stale issues and are trying to determine if this can be closed. Do you have an insight into whether this issue was resolved?

**Comment by jpower432** [comment]
Closing this as performance issues have not been reported.
