### ISSUE TITLE
As a trestle user I want to be able to setup `a bare` repositories which only support a subset of file types.

### ISSUE THREAD

**Issue by butler54** [oscal-compass/compliance-trestle#352]
## Issue description / feature objectives
Today `trestle init` creates a `full` directory tree - that is folders for every top level schema.
For users of the trestle author functionality a `--bare` or similar argument would be useful to minimise double handling.

### Side effects:
- Commands like `trestle import` need to be able to automatically create directories as required (mkdir with parents).

**Comment by butler54** [comment]
Thinking this through a bit more .. something like  `trestle init --bare` would be great.

The precondition would be the set of trestle commands will need to be reworked to create the necessary directories on demand.

**Comment by jpower432** [comment]
This is partially done. `trestle init --govdocs` will effectively do this. Closing and the side effect will go onto a separate issue.
