### ISSUE TITLE
As a external user I want a mechanism where I can pass a 'full' SSP and automatically match an existing split.

### ISSUE THREAD

**Issue by butler54** [oscal-compass/compliance-trestle#444]
## Issue description / feature objectives
in issue #395 it is identified that it would be fantastic if a GRC tool can 'update' a trestle project, however, given this it needs be able to update 'over' a directory structure. 

For this to happen trestle needs to be able to take a fully formed object from the GRC tool and 'discover' the current split of a catalog/ssp/etc and be able to overwrite the current format.

## Completion Criteria
Functionality is exposed as a functional interface to the end developer
##

**Comment by AleJo2995** [comment]
@butler54 Could you please expand a little bit more here on the use case? Thanks
