### ISSUE TITLE
Create demonstrations of using trestle as a pre-commit hook.

### ISSUE THREAD

**Issue by butler54** [oscal-compass/compliance-trestle#475]
As a trestle user it would be fantastic if trestle can run , for certain operations, as a pre-commit hook. 

Trestle is not optimised for pre-commit, however, pre-commit can easily be configured for trestle. Provide an example in the compliance-trestle-demos project.

**Comment by butler54** [comment]
Based on the way trestle is working I recommend that we change this to a documentation issue.

**Comment by vikas-agarwal76** [comment]
Do validation using trestle during commit.

**Comment by AleJo2995** [comment]
@butler54 We were reviewing stale issues and we were wondering we should move/transfer this issue to the demos repo, will that work for you in this case? Thanks

**Comment by jpower432** [comment]
Closing. This would take a lot of engineering work and is outside the scope of the project.
