### ISSUE TITLE
Evaluate https://pypi.org/project/saxonpy/ for use with compliance-trestle-fedramp

### ISSUE THREAD

**Issue by butler54** [oscal-compass/compliance-trestle#947]
## Issue description / feature objectives
It looks like someone has created an installable wheel of saxon. This will make life much easier on at least linux and mac (but not windows). Evaluate using this for compliance-trestle-fedramp.

**Comment by butler54** [comment]
and update the setup.cfg. It looks like windows will still need a manual install.

**Comment by jpower432** [comment]
@butler54 @vikas-agarwal76 Recommending we close this issue. It was accomplished through this [PR](https://github.com/oscal-compass/compliance-trestle-fedramp/pull/21/files#). Using https://pypi.org/project/saxonche/.
